### ISSUE TITLE
Filter_parameters require all lower case to work

### ISSUE THREAD

**Issue by MajesticFalcon** [wvandeun/nornir_netbox#31]
In limited testing, it seems that the filter_parameters need to be all lowercase. 

Example:
    Netbox:
       Site: Checkaboo
    Nornir_netbox
        'filter_parameters': {'site', 'checkaboo'}

Whereas netbox filters based on "Site", nornir_netbox will throw an error. You seem to need lowercase for it to work. I suspect this may be a nornir_netbox issue as I can filter with "Site" in netbox.

**Comment by wvandeun** [comment]
Not convinced this is an issue of the plugin.

`nornir_netbox` uses the `limit=0` url parameter, so that netbox returns the maximum amount of records in 1 response (depending on how netbox is setup). 
This is the first parameter we pass.

In your case the url that we call would be `https://yournetbox.instance/api/dcim/devices/?limit=0&Site=checkaboo`. NetBox doesn't seem to filter the data on that site attribute.

However if you leave out the limit parameter then it works `https://yournetbox.instance/api/dcim/devices/?Site=checkaboo`

Not even sure why the upper case S even works, since attributes of a device in NetBox's model are all lower cased.
