### ISSUE TITLE
Adding region to device groups

### ISSUE THREAD

**Issue by j1ves** [wvandeun/nornir_netbox#33]
been using this module and noticed that the device is missing the region from the groups, this would be very handy.

**Comment by wvandeun** [comment]
While I understand that is useful. I'm not sure if that is going to be immediately possible.

The Device model in NetBox has no direct relation to a region. A Device has a relation to a Site, which has a relation to a region and that region could then have a relation to another region and so forth.

The API endpoint we use in the plugin is `api/dcim/devices`. It only gives you the base data of a site, but doesn't show any region information. 
That means we would need to add additional API calls to `api/dcim/sites` and `api/dcim/regions` to get all of that relations and inject it into our target data structure.

This would potentially make it slow, depending on the size of your db.

I have been looking into the GraphQL implementation of NetBox. Through this API it would be possible to get that data in a single API call. I'm looking if we can add another inventory class that would allow us to use GraphQL as the backend API.
It would then be up to the user to define the GraphQL query, so that you can partially control which data you receive in the Nornir inventory.

But I need to give this a bit more thought and it is going to require some time before I get there.
